### ISSUE TITLE
RangeError 

### ISSUE THREAD

**Issue by abozhilov** [mathiasbynens/String.prototype.repeat#7]
According to ES: 

15.4.2.2 new Array (len)
.....
If the argument len is a Number and ToUint32(len) is equal to len, then the length property of the newly 
constructed object is set to ToUint32(len). If the argument len is a Number and ToUint32(len) is not equal to len, 
a RangeError exception is thrown.

 This is not correct test: 

if (n < 0 || n == Infinity) {
    throw RangeError();
}

e.g 'test'.repeat(Math.pow(2, 33)); must throws RangeError. 

Better use: 
if ((n >>> 0) !== n) {
    throw RangeError();
}

**Comment by nicolo-ribaudo** [comment]
Is this still the case? I can't find any reference to that limitation in the spec of `String.prototype.repeat`
